### PR TITLE
Add support for delimiter patterns and fix Clojure (Fix #77)

### LINKED ISSUE #77: Clojure Class Sorting
**Describe the bug**

The LSP is being called with the quotes, and I think it's treating them as if they're part of the class names.

Image

**To Reproduce**

Add something like this in Clojure and call `:TailwindSort`.
```clojure
[:div {:class "cls-1 cls-2 cls-3"}]
```
it then gets sorted like this, with the quotes always being around the first two classes.
```clojure
[:div {:class "cls-1 cls-2" cls-3}]
```

**Expected behavior**
Only inner string should be sorted

**Environment (please complete the following information):**
 - Mac OS
 - NVIM v0.11.0
 - tree-sitter 0.25.3
 - tailwind-language-server 0.14.16

**Additional context**
Working on updating the tree sitter query at the moment 👀

### PR DESCRIPTION
**Pull request by garrett-hopper**
This removes the Clojure treesitter schema which was causing issues in #77.

Instead, a few patterns are introduced. In addition to the previously supported `{:class "..."}` syntax, `^:tw` strings and Hiccup style `[:div#id.cls-1.cls-2]` class shorthand is now supported.

The Hiccup syntax required me to add a `{ pattern = "...", delimiter = "%." }` syntax which is used to replace the delimiter with spaces before calling `tailwindCSS/sortSelection` and is recombined with the delimiter after sorting is complete.

I'm not sure what other languages would use this style of class names separated by non-spaces. (Perhaps something Emmet inspired? 🤷)

I also updated `get_patterns` to prefer the user provided patterns if available to allow my local config to define other custom patterns which wouldn't make sense in the plugin's patterns. (Not sure if the user's patterns should be merged with or override the plugin's patterns)

I don't believe the `delimiter` support should impact the efficiency or usage by other languages which don't use it. (Other than checking if each range happens to have a `delimiter` defined on it, but that should be very fast.)

Note: These patterns also need to be in `experimental.classRegex` to get LSP support for them. Not sure if it's worth having this plugin default `classRegex` for any languages.

Here's the config I'm using

```lua
  {
    "luckasRanarison/tailwind-tools.nvim",
    opts = {
      server = {
        settings = {
          includeLanguages = {
            clojure = "html",
          },
          experimental = {
            classRegex = {
              -- :class "cls-1 cls-2"
              [[:class\s+"([^"]+)"]],
              -- ^:tw "cls-1 cls-2"
              [[\^:tw\s+"([^"]+)"]],
              -- [:div#id.cls-1.cls-2] [:#id.cls-1.cls-2] [:.cls-1.cls-2]
              { [[\[:[\w-]*#?[\w-]*\.([\.\w-]+)]], [[([\w-]+)]] },
              -- :.cls-1.cls-2
              { [[:\.([\.\w-]+)]], [[([\w-]+)]] },
            },
          },
        },
      },
      extension = {
        patterns = {
          clojure = {
            -- :class "cls-1 cls-2"
            ':class%s+"([^"]+)"',
            -- ^:tw \"cls-1 cls-2\"
            '%^:tw%s+"([^"]+)"',
            -- [:div#id.cls-1.cls-2] [:#id.cls-1.cls-2] [:.cls-1.cls-2]
            { pattern = "%[:[%w%-]*#?[%w%-]*%.([%.%w%-]+)", delimiter = "." },
            -- :.cls-1.cls-2
            { pattern = [[:%.([%.%w%-]+)]], delimiter = "." },
          },
        },
      },
    },
  },
```

I've tried to keep the `classRegex` I'm using relatively similar to the Lua patterns to ensure it's clear that wherever the LSP is working, the pattern based class sorting should too. However, there are a few differences between the two. (The patterns specifically don't capture the initial `.` for Hiccup classes so the code doesn't have to handle a prefix delimiter.)

### CODE REVIEW

**Comment by luckasRanarison** [comment]
Sorry for the late reply. This is a pretty interesting usecase and addition, that delimiter option is definitely useful. Great work and thanks for the PR!

Everything looks good to me but you should keep the test file for clojure, or update it.

File: tests/queries/clojure_spec.lua [hunk 1]
```diff
@@ -1,12 +0,0 @@
-local runner = require("tests.queries.runner")
-
-runner.test({
-  name = "closure",
-  provider = "treesitter",
```
Comment (luckasRanarison) [inline tests/queries/clojure_spec.lua:5]: You should update this with luapattern.

**Review by luckasRanarison — CHANGES_REQUESTED** [review]

**Comment by garrett-hopper** [comment]
My bad, Clojure test added back. (Saw it was in `queries` and thought it was all Tree-sitter specific)

I'm debating how to handle the `:class []` syntax. Previously the entire TS node following `:class` was included. My new version is more restrictive, only allowing standard `:class "cls-1 cls-2"` and `[:div#id.cls-1.cls-2]` syntax.

For my personal use, I use `^:tw` metadata on strings I need TW support in. Not sure if that's worth making default in here though, since it's non-standard. I'm not sure I'd want every string/keyword that happens to be a child of a `:class` value to be assumed to be tailwind. 🤔 (Realistically most people won't have deeply nested logic in that position though. 🤷)

This feels like a safe default to me, and if people want to define in their own config the syntax they want to use beyond those two builtins.

```lua
    extension = {
      patterns = {
        clojure = {
          -- :class "cls-1 cls-2"
          ':class%s+"([^"]+)"',
          -- ^:tw \"cls-1 cls-2\"
          '%^:tw%s+"([^"]+)"',
          -- [:div#id.cls-1.cls-2] [:#id.cls-1.cls-2] [:.cls-1.cls-2]
          { pattern = "%[:[%w%-]*#?[%w%-]*%.([%.%w%-]+)", delimiter = "." },
          -- :.cls-1.cls-2
          { pattern = [[:%.([%.%w%-]+)]], delimiter = "." },
        },
      },
    },
```

**Comment by luckasRanarison** [comment]
> Also realizing this probably could've been implemented as TS query with a #set! directive for the captures that need it. 
Yeah, that would also work. Actually, I already use some custom directives so I don't think it should be that hard. I may add that myself when I have some time.

> I'm debating how to handle the :class [] syntax. Previously the entire TS node following :class was included. My new version is more restrictive, only allowing standard :class "cls-1 cls-2" and [:div#id.cls-1.cls-2] syntax.
Excuse me, could you illustrate with an example and explain the tricky part about it? I'm not using clojure actually, I just added it at some point.

**Review by luckasRanarison — APPROVED** [review]

**Comment by luckasRanarison** [comment]
This looks good to me for now so merging it, we can add delimiter to treesitter later. Thanks again for the PR!

**Comment by garrett-hopper** [comment]
> Excuse me, could you illustrate with an example and explain the tricky part about it? I'm not using clojure actually, I just added it at some point.

In Clojure, I could have arbitrary code within the `:class` vector. Currently, to get completions within strings in that vector, I prefix the strings with `^:tw` (Clojure metadata) to get completions.

```clojure
(defn Example [x]
  [:div {:class [^:tw "text-green-500"
                 (if (= x "red")
                   ^:tw "bg-red-500"
                   ^:tw "bg-blue-500")]}])
```

If instead I were to match all strings within the vector, then `"red"` would incorrectly be interpreted as a tailwind class string.

```clojure
(defn Example [x]
  [:div {:class ["text-green-500"
                 (if (= x "red") ; <-- "red" is not intended to be a tailwind class string
                   "bg-red-500"
                   "bg-blue-500")]}])
```

I think there's probably some heuristic of only matching strings (and maybe keywords) in tail position for tailwind classes. (E.g. not matching strings inside of conditionals, though that'd require more complex parsing than Clojure's tree-sitter grammar currently performs and would be flaky for those with custom macros. Using `^:tw` supports all these cases since it explicitly tags strings that are intended to be tailwind; it's just a bit verbose.)
